#!/bin/sh
# prerm script for abc
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|upgrade|deconfigure)
        DIR='/var/lib/squidguard/db'
        if test -L $DIR;then
            rm -f $DIR
        fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
