#!/bin/sh
#
# AUTHOR: Pedro Lineu Orso                         pedro.orso@gmail.com
#                                                            1998, 2009
# SARG Squid Analysis Report Generator      http://sarg.sourceforge.net
#
# SARG donations:
#      please look at http://sarg.sourceforge.net/donations.php
# ---------------------------------------------------------------------
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
#
#

conf="/usr/local/sarg/sarg.conf"
squid_password_file="/usr/local/squid/etc/passwd"
tmp="/tmp/sarg_limit.$$"

limit_file=`grep "per_user_limit" $conf|grep -v "#"|awk '{print $2}'`

if [ "$limit_file" != "" ]; then
   rm -rf $tmp
   cat $limit_file|while read key; do
      uline=`grep $key $squid_password_file`
      grep -v $key $squid_password_file > $tmp
      echo $uline|sed 's/:/:*/g' >> $tmp
      cat $tmp > $squid_password_file
      rm -rf $tmp
   done
fi
