plugins/controle_web/backend.py	var/lib/netcontrol/plugins/controle_web/
plugins/controle_web/files	var/lib/netcontrol/plugins/controle_web/
plugins/controle_web/__init__.py	var/lib/netcontrol/plugins/controle_web/
plugins/controle_web/layout	var/lib/netcontrol/plugins/controle_web/
plugins/controle_web/main.py	var/lib/netcontrol/plugins/controle_web/
plugins/controle_web/templates	var/lib/netcontrol/plugins/controle_web/
