#!/bin/bash
# postinst script for netcontrol

set -e

case "$1" in
    configure)
        update-rc.d netcontrol-backup defaults
        netcontrol-pkg upgrade
	/etc/init.d/netcontrol restart || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        update-rc.d -f netcontrol remove || true
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
