plugins/ldap_server/backend.py	var/lib/netcontrol/plugins/ldap_server/
plugins/ldap_server/createMachine.py	var/lib/netcontrol/plugins/ldap_server/
plugins/ldap_server/files	var/lib/netcontrol/plugins/ldap_server/
plugins/ldap_server/__init__.py	var/lib/netcontrol/plugins/ldap_server/
plugins/ldap_server/layout	var/lib/netcontrol/plugins/ldap_server/
plugins/ldap_server/main.py	var/lib/netcontrol/plugins/ldap_server/
