plugins/supervisor/client.py	var/lib/netcontrol/plugins/supervisor/
plugins/supervisor/files	var/lib/netcontrol/plugins/supervisor/
plugins/supervisor/__init__.py	var/lib/netcontrol/plugins/supervisor/
plugins/supervisor/layout	var/lib/netcontrol/plugins/supervisor/
plugins/supervisor/main.py	var/lib/netcontrol/plugins/supervisor/
plugins/supervisor/widget.py	var/lib/netcontrol/plugins/supervisor/
